name: dart_bech32
description: A BIP173 / BIP350 compatible Bech32/Bech32m encoding/decoding library.
version: 1.0.1
homepage: https://github.com/dart-bitcoin-lib/dart-bech32
repository: https://github.com/dart-bitcoin-lib/dart-bech32

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  convert: ^3.0.1
